spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spamfilter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Andre622@
  jpa:
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.generate_statistics: false
      show-sql: false  # big speed boost vs console spam
    
    mvc:
        log-request-details: false

server:
  port: 8080

  server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param   # add ?trace=true to see stack

logging:
  level:
    com.example.server: DEBUG
    org.hibernate.SQL: WARN
    org.springframework.web.filter.CommonsRequestLoggingFilter: OFF
    root: INFO
    org.springframework.web: INFO
    com.example.server.email: INFO


email:
  host: ${EMAIL_HOST:imap.mail.yahoo.com}
  port: ${EMAIL_PORT:993}
  ssl: ${EMAIL_SSL:true}
  folder: ${EMAIL_FOLDER:INBOX}
  username: ${EMAIL_USER:dbd622@yahoo.com}   # leave blank by default so app still starts
  password: ${EMAIL_PASS:mnuobohudkvvjssv}   # set via env var before calling the endpoint
  max: ${EMAIL_MAX:5}
  


