spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spamfilter?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    password: Andre622@
=======
    password: *********
>>>>>>> Stashed changes
=======
    password: *********
>>>>>>> Stashed changes
  jpa:
    hibernate:
      ddl-auto: update   # good for development; use migrations later in prod
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
<<<<<<< Updated upstream
<<<<<<< Updated upstream

  server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param   # add ?trace=true to see stack

logging:
  level:
    com.example.server: DEBUG
    org.springframework.web: DEBUG


email:
  host: ${EMAIL_HOST:imap.mail.yahoo.com}
  port: ${EMAIL_PORT:993}
  ssl: ${EMAIL_SSL:true}
  folder: ${EMAIL_FOLDER:INBOX}
  username: ${EMAIL_USER:dbd622@yahoo.com}   # leave blank by default so app still starts
  password: ${EMAIL_PASS:mnuobohudkvvjssv}   # set via env var before calling the endpoint
  max: ${EMAIL_MAX:5}
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
